apiVersion: v1
kind: Service
metadata:
  name: my-mysql-svc
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
# persistent storage for the db
kind: StatefulSet
metadata:
  name: my-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: "my-mysql-svc"
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.39-debian
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysqldb
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "changeme"
          - name: MYSQL_DATABASE
            value: "character_register"
  volumeClaimTemplates:
  - metadata:
      name: mysqldb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi
